version: '3.8'
name: fluentpos-lite

services:
  # Gateway
  gateway:
    container_name: "gateway"
    image: fluentpos-lite.gateway:latest
    ports:
      - 5010:5010
      - 5100:5100
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=https://+:5100;http://+:5010
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https
    networks:
     - fluentpos-lite
  
  # Identity 
  identity:
    container_name: identity
    image: fluentpos-lite.identity:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https
    depends_on:
      postgres:
        condition: service_healthy 
    networks:
     - fluentpos-lite

  # Catalog
  catalog:
    container_name: catalog-service
    image: fluentpos-lite.catalog:latest
    depends_on:
      - mongo
      - placement
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https
    networks:
     - fluentpos-lite
  catalog-dapr:
    container_name: catalog-dapr
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "catalog",
     "-placement-host-address", "placement:50006",
     "-app-port", "80",
     "-components-path", ".././dapr"]
    volumes:
      - ".././dapr/:/dapr" 
    depends_on:
      - catalog
    network_mode: "service:catalog"